version: "3.7"

services:
  order-service:
    container_name: order-service
    image: order-service
    depends_on:
      - customer-service
      - product-service
    environment:
      - CUSTOMER_SERVICE_HOST=customer-service
      - PRODUCT_SERVICE_HOST=product-service
    ports:
      - 9000:9000

  customer-service:
    container_name: customer-service
    image: customer-service
    ports:
      - 9090:9090

  product-service:
    container_name: product-service
    image: product-service
    ports:
      - 9091:9091
