version: '3.7'

services:
  order-service:
    container_name: order-service
    image: order-service
    depends_on:
      - customer-service
    ports:
      - 9000:9000

  customer-service:
    container_name: customer-service
    image: customer-service
    ports:
      - 9090:9090