apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
        env: development
    spec:
      containers:
        - name: customer-service
          image: eu.gcr.io/ssil1-258911/customer-service:v1
          ports:
            - containerPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
        env: development
    spec:
      containers:
        - name: product-service
          image: eu.gcr.io/ssil1-258911/product-service:v1
          ports:
            - containerPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
        env: development
    spec:
      containers:
        - name: order-service
          image: eu.gcr.io/ssil1-258911/order-service:v1
          ports:
            - containerPort: 9000
          env:
            - name: CUSTOMER_SERVICE_HOST
              value: "customer-service"
            - name: PRODUCT_SERVICE_HOST
              value: "product-service"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: customer-service
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app: product-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: order-service