apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
        env: development
    spec:
      containers:
        - name: customer-service
          image: eu.gcr.io/ssil1-258911/customer-service:v1
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: customer-service